# Generated by Django 4.1.6 on 2023-02-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('grand_father_name', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('POB', models.CharField(help_text='place of birth', max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('id_card', models.FileField(upload_to='uploadedId')),
                ('attachement', models.FileField(upload_to='uploadedAttachements')),
                ('other_notes', models.CharField(max_length=500)),
            ],
        ),
    ]
